from typing import Dict
import typing

id_lookup_table: Dict[str, int] = {
    "Kill Knuckle Dragger": 3333001,
    "Kill Boom": 3333002,
    "Kill Bewm": 3333003,
}

boss_lookup_table: list[str] = [
    "Bloodwing",
    "BNK3R",
    "Handsome Jack",
    "The Warrior",
    "Wilhelm",
    "Bad Maw",
    "Boom",
    "Bewm",
    "Captain Flynt",
    "Gluttonous Thresher",
    "Jack's Body Double",
    "Knuckle Dragger",
    "Mortar",
    "Saturn",
    "W4R-D3N",
    "Assassin Oney",
    "Assassin Reeth",
    "Assassin Rouf",
    "Assassin Wot",
    "Bagman",
    "The Black Queen",
    "Blue",
    "Boll",
    "Bone Head 2.0",
    "Deputy Winger",
    "Doc Mercy",
    "Donkey Mong",
    "Dukino's Mom",
    "Flinter",
    "Foreman Jasper",
    "Gettle",
    "Henry",
    "Hunter Hellquist",
    "Incinerator Clayton",
    "Jimmy Jenkins",
    "King Mong",
    "Laney White",
    "Madame Von Bartlesby",
    "Mad Mike",
    "Mad Dog",
    "Mal",
    "McNally",
    "Mick Zaford",
    "Midgemong",
    "Mobley",
    "Muscles",
    "Old Slappy",
    "Pimon",
    "Prospector Zeke",
    "Rakkman",
    "Requisition Officer",
    "Savage Lee",
    "Scorch",
    "Sheriff of Lynchwood",
    "Shorty",
    "Sinkhole",
    "Smash Head",
    "Son of Mothrakk",
    "Splinter Group",
    "Spycho",
    "Tector & Jimbo Hodunk",
    "Terramorphous the Invincible",
    "Tumbaa",
    "Vermivorous the Invincible"
]